### ISSUE TITLE
Click element to select Vue component

### ISSUE THREAD

**Issue by petridw** [dperrymorrow/electron-vue-debugger#2]
Feature request

Ability to click on an element in the dom and have debugger select & expand the most direct parent component of the clicked element.

Would be somewhat straightforward to recurse through component tree for the element and see if any components have that element as their $el. If not, go to the element's parent and check the component tree again.

You could make it more efficient when recursing component tree by checking if $el.contains(element) is false, if so you could just break recursion there and ignore that entire component tree.

**Comment by dperrymorrow** [comment]
merged and released
